apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb
  namespace: openedx
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: database
automountServiceAccountToken: false
