apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongodb
  namespace: openedx
  labels:
    app.kubernetes.io/name: mongodb
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
