apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mongodb-pdb
  namespace: openedx
  labels:
    app.kubernetes.io/name: mongodb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb
