apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongodb-storage
  labels:
    app.kubernetes.io/name: mongodb
provisioner: ebs.csi.aws.com          # ← change for your cloud
parameters:
  type: gp3
  iops: "3000"
  throughput: "125"
  encrypted: "true"
reclaimPolicy: Retain                 # CRITICAL – keeps data even if PVC is deleted
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
