# =============================================================================
# 10. SERVICE MONITOR  (Prometheus Operator)
#     Remove this section if you're not using prometheus-operator.
#     The label "release: prometheus" must match your Prometheus CR's
#     serviceMonitorSelector.
# =============================================================================
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongodb
  namespace: openedx
  labels:
    app.kubernetes.io/name: mongodb
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb
  namespaceSelector:
    matchNames:
      - openedx
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
      path: /metrics
